# Generated by Django 5.0.3 on 2024-03-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cse', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cse', max_length=100)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sch_class', to='testapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
                ('roll', models.IntegerField(default=1)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cls_student', to='testapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Liberary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lib', max_length=100)),
                ('students', models.ManyToManyField(blank=True, related_name='students_names', to='testapp.student')),
            ],
        ),
    ]
