version: '3'
services:    
  das:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    # environment:
    #   REDIS_ARGS: "--requirepass redis"
